### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by silence-coding** [tikv/jemallocator#8]
This problem occurs occasionally. No condition for reoccurring the problem is found, and the binary system is not damaged.

**Platform**
Linux OMP-01 4.18.0-147.5.1.6.h451.eulerosv2r9.x86_64 #1 SMP Thu Apr 22 04:55:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

```
Program terminated with signal 11, Segmentation fault.
#0  atomic_load_p (mo=atomic_memory_order_acquire, a=<optimized out>) at ../jemalloc/include/jemalloc/internal/atomic.h:55
55	../jemalloc/include/jemalloc/internal/atomic.h: No such file or directory.
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) bt
#0  atomic_load_p (mo=atomic_memory_order_acquire, a=<optimized out>) at ../jemalloc/include/jemalloc/internal/atomic.h:55
#1  extent_arena_get (extent=<optimized out>) at ../jemalloc/include/jemalloc/internal/extent_inlines.h:49
#2  _rjem_je_tcache_bin_flush_small (tsd=tsd@entry=0x7fd7f77fdb80, tcache=tcache@entry=0x7fd7f77fdd40, 
    tbin=tbin@entry=0x7fd7f77fde70, binind=binind@entry=12, rem=16) at ../jemalloc/src/tcache.c:148
#3  0x000055830c50e146 in tcache_dalloc_small (slow_path=false, binind=12, ptr=0x7fd7f7c2c800, tcache=0x7fd7f77fdd40, 
    tsd=<optimized out>) at ../jemalloc/include/jemalloc/internal/tcache_inlines.h:178
#4  arena_sdalloc (slow_path=false, alloc_ctx=0x0, tcache=0x7fd7f77fdd40, size=<optimized out>, ptr=0x7fd7f7c2c800, 
    tsdn=<optimized out>) at ../jemalloc/include/jemalloc/internal/arena_inlines_b.h:336
#5  isdalloct (slow_path=false, alloc_ctx=0x0, tcache=0x7fd7f77fdd40, size=<optimized out>, ptr=0x7fd7f7c2c800, 
    tsdn=<optimized out>) at ../jemalloc/include/jemalloc/internal/jemalloc_internal_inlines_c.h:131
#6  isfree (slow_path=false, tcache=0x7fd7f77fdd40, usize=<optimized out>, ptr=0x7fd7f7c2c800, tsd=0x7fd7f77fdb80)
    at ../jemalloc/src/jemalloc.c:2280
#7  _rjem_sdallocx (ptr=0x7fd7f7c2c800, size=<optimized out>, flags=<optimized out>) at ../jemalloc/src/jemalloc.c:3017
#8  0x000055830c2009e6 in core::ptr::drop_in_place::h39946e6441c8a0f8 ()
#9  0x000055830c200938 in core::ptr::drop_in_place::h39946e6441c8a0f8 ()
#10 0x000055830c20083a in core::ptr::drop_in_place::h39946e6441c8a0f8 ()
#11 0x000055830c200aa1 in core::ptr::drop_in_place::h39946e6441c8a0f8 ()
#12 0x000055830c200938 in core::ptr::drop_in_place::h39946e6441c8a0f8 ()
#13 0x000055830c20089e in core::ptr::drop_in_place::h39946e6441c8a0f8 ()
#14 0x000055830c20096c in core::ptr::drop_in_place::h39946e6441c8a0f8 ()
#15 0x000055830c200a6d in core::ptr::drop_in_place::h39946e6441c8a0f8 ()
#16 0x000055830c200938 in core::ptr::drop_in_place::h39946e6441c8a0f8 ()
#17 0x000055830c20080d in core::ptr::drop_in_place::h39946e6441c8a0f8 ()
#18 0x000055830c20096c in core::ptr::drop_in_place::h39946e6441c8a0f8 ()
#19 0x000055830c20086a in core::ptr::drop_in_place::h39946e6441c8a0f8 ()
#20 0x000055830c20089e in core::ptr::drop_in_place::h39946e6441c8a0f8 ()
#21 0x000055830c20086a in core::ptr::drop_in_place::h39946e6441c8a0f8 ()
#22 0x000055830c20096c in core::ptr::drop_in_place::h39946e6441c8a0f8 ()
#23 0x000055830c20086a in core::ptr::drop_in_place::h39946e6441c8a0f8 ()
#24 0x000055830c210959 in core::ptr::drop_in_place::ha7d503c0d4aab3e5 ()
#25 0x000055830c4261db in alloc::sync::Arc$LT$T$GT$::drop_slow::he95700ee504b005b ()
#26 0x000055830becd6c1 in _$LT$core..future..from_generator..GenFuture$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$::pol---Type <return> to continue, or q <return> to quit---
l::h1f5fc0d685c33b92 ()
#27 0x000055830bda9d42 in _$LT$futures_util..stream..unfold..Unfold$LT$T$C$F$C$Fut$GT$$u20$as$u20$futures_core..stream..Stream$GT$::poll_next::ha86319c9c67d0585 ()
#28 0x000055830bedcc76 in _$LT$core..future..from_generator..GenFuture$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$::poll::h48ad42ec62bc6329 ()
#29 0x000055830c35574d in tokio::task::core::Core$LT$T$GT$::poll::h2d67eee65241029c ()
#30 0x000055830bb39acd in tokio::task::harness::Harness$LT$T$C$S$GT$::poll::h794b636ffb809ea5 ()
#31 0x000055830c824d6f in tokio::runtime::thread_pool::worker::GenerationGuard::run_task::hd657e88f8ba7ce5d ()
#32 0x000055830c8243df in tokio::runtime::thread_pool::worker::GenerationGuard::run::h132b5d9748a652f3 ()
#33 0x000055830c81c291 in std::thread::local::LocalKey$LT$T$GT$::with::hc53944dca76bd295 ()
#34 0x000055830c8241a7 in tokio::runtime::thread_pool::worker::Worker::run::h66bdcf9450037f90 ()
#35 0x000055830c83d71a in tokio::task::core::Core$LT$T$GT$::poll::h37557b3d79ec35ad ()
#36 0x000055830c84336a in tokio::task::harness::Harness$LT$T$C$S$GT$::poll::h62f0931a6dbf0caa ()
#37 0x000055830c82ccbb in tokio::runtime::blocking::pool::Inner::run::h2ddfe0c35845e7d5 ()
#38 0x000055830c826c18 in tokio::runtime::context::enter::he504003b159f3fe5 ()
#39 0x000055830c8408ee in std::sys_common::backtrace::__rust_begin_short_backtrace::h73de78c1b3e9192d ()
#40 0x000055830c82f7e2 in core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h7e8bb59df00be403 ()
#41 0x000055830c894bda in call_once<(),FnOnce<()>> ()
    at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/liballoc/boxed.rs:1076
#42 call_once<(),alloc::boxed::Box<FnOnce<()>>> ()
    at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/liballoc/boxed.rs:1076
#43 std::sys::unix::thread::Thread::new::thread_start::hf745c8cf29a89648 () at src/libstd/sys/unix/thread.rs:87

```

**Comment by BusyJay** [comment]
What version did you use? It didn't seem like to match the code in this crate.

**Comment by silence-coding** [comment]
Sorry, I'm using gnzlbg/jemallocator and haven't switched tikv yet

**Comment by silence-coding** [comment]
If tikv doesn't involve this error, then I'll turn issue off.

**Comment by BusyJay** [comment]
We have not observed any thing similar yet.
